### ISSUE TITLE
Bootstrap 3 support

### ISSUE THREAD

**Issue by tim0t** [andresgutgon/bootstrap-tooltip-extension#3]
This plugin doesn't work with Bootstrap 3. 

It doesn't place the normal tooltip options like "top" in the correct position and the arrows for these elements are gone. 

![screen](https://cloud.githubusercontent.com/assets/6942472/3171361/7fa66fce-ebc5-11e3-8ce3-6ff74a7ad4b1.png)

I also tried to include the named bootstrap-tooltip.js but no result. I think the tooltip is now included in Bootstrap. To make it work a bit I also needed to initialize the plugin like the example down here: 

```
$('.tooltip-visible[data-placement="top-right"]').tooltip({
    trigger: 'manual', 
    animation: false,
    template: '<div class="tooltip top-right">
                <div class="tooltip-arrow"></div>
                <div class="tooltip-inner"></div>
               </div>'
}).tooltip('show');    
```

Do you have a solution for this? Thanks a lot!

**Comment by andresgutgon** [comment]
Sorry for not responding
This lib is no longer maintained. I'm using https://popper.js.org for position tooltip/popover on a screen. It doesn't manage clicks just positioning but it does very well
