### ISSUE TITLE
Tooltip.js

### ISSUE THREAD

**Issue by FezVrasta** [andresgutgon/bootstrap-tooltip-extension#6]
You may find this useful:

https://github.com/FezVrasta/popper.js/tree/v1-dev#tooltipjs

**Comment by andresgutgon** [comment]
I knew popper :)

Btw I'm not maintaning this repo anymore

**Comment by FezVrasta** [comment]
I just wanted to point you to Tooltip.js, which is a new library that does all would you expect from a tooltip library (hover, click, hide, show, toggle etc).

Cheers!

**Comment by andresgutgon** [comment]
oh! Thanks I didn't get it :)
